### ISSUE TITLE
Support for Angular 5+

### ISSUE THREAD

**Issue by lvidal1** [flauc/angular2-notifications#272] opened 2017-11-11 04:02 UTC
### This is a...

* [x] feature request
* [ ] bug report
* [ ] usage question

### Additional Notes:

Currently this project does not support Angular 5.0.
Is there any pre-release that does?

What do we need to change to implement the support?

**Comment by StasGoshtein** [comment] 2017-11-12 18:29
+1

**Comment by flauc** [comment] 2017-11-13 17:20
The newest version should support Angular 5 out of the box. I'm using @angular/cli for testing to it might not work in all environments though. If it isn't working for you can you please create a plunkr with the error replicated?

**Comment by AndreiZaman** [comment] 2017-11-17 08:55
Looks like the problem is here:
Per Angular's changelog:
https://github.com/angular/angular/blob/master/CHANGELOG.md
OpaqueToken has been removed as it was deprecated since v4. Use InjectionToken instead.

**Comment by flauc** [comment] 2017-11-17 09:05
Thank you @AndreiZaman,

`OpaqueToken` isn't used anywhere in the library. If you have it in your project that might be what's causing the error. 

I'm closing the issue, if you continue to have problems please create a plunkr recreating the issue.

**Closed by flauc** 2017-11-17 09:05 UTC
