### ISSUE TITLE
icon padding is missing in version 0.9.7

### ISSUE THREAD

**Issue by sschustar** [flauc/angular2-notifications#290] opened 2018-01-11 06:49 UTC
Hello,

the layout of the notification is broken in version 0.9.7 as the icon padding is missing.

The problem seems to be in `notification.component.css`. The CSS selector for the icon padding style is `.simple-notification.has-icon .sn-content` but the class `has-icon` is missing in the DOM so the style is never applied.

Best regards

**Comment by georgique** [comment] 2018-01-11 15:48
Confirmed.
And another thing - if I add `has-icon` class, then header `line-height` reduces to 20px, whereas it should be 30px.

**Comment by blackholegalaxy** [comment] 2018-03-07 19:26
Since PR was merged, can this issue be closed?

**Comment by flauc** [comment] 2018-04-01 16:59
Yes this has been resolved, thank you @georgique

**Closed by flauc** 2018-04-01 16:59 UTC
