### ISSUE TITLE
Webpack issues: Module build failed: Error: Typescript emitted no output for ...

### ISSUE THREAD

**Issue by dessalines** [flauc/angular2-notifications#134] opened 2017-01-10 21:54 UTC
I recently upgraded angular to `2.4.1`, and angular2-notifications to `0.4.49`, and now I'm getting the following errors when I run webpack:

```sh
    ERROR in ./~/angular2-notifications/src/push-notifications.service.ts
    Module build failed: Error: Typescript emitted no output for /home/asdf/git/asdf/node_modules/angular2-notifications/src/push-notifications.service.ts
        at Object.loader (/home/asdf/git/asdf/node_modules/ts-loader/index.js:437:15)
     @ ./~/angular2-notifications/components.js 14:35-78
    
    ERROR in ./~/angular2-notifications/src/notifications.service.ts
    Module build failed: Error: Typescript emitted no output for /home/asdf/git/asdf/node_modules/angular2-notifications/src/notifications.service.ts
        at Object.loader (/home/asdf/git/asdf/node_modules/ts-loader/index.js:437:15)
     @ ./~/angular2-notifications/components.js 8:30-68
    
    ERROR in ./~/angular2-notifications/src/max.pipe.ts
    Module build failed: Error: Typescript emitted no output for /home/asdf/git/asdf/node_modules/angular2-notifications/src/max.pipe.ts
        at Object.loader (/home/asdf/git/asdf/node_modules/ts-loader/index.js:437:15)
     @ ./~/angular2-notifications/components.js 10:17-42
    Warning: Task "webpack:dev" failed. Use --force to continue.
```

**Comment by flauc** [comment] 2017-01-10 22:27
Hmm, first time I see this. Thanks for reporting it. I'll look in to it. 👍

**Comment by dotixx** [comment] 2017-01-25 13:06
Same issue here :s

**Comment by tscislo** [comment] 2017-02-04 21:10
Same issue using Angular 2.4.0 with webpack 1.13.2 and TS 2.1.4

**Comment by totycro** [comment] 2017-02-24 14:05
I'd like to use angular2-notifications, but can't because of this bug.. do you have any idea when it can be fixed?

**Comment by rafaeltmc** [comment] 2017-02-24 14:22
similar here with angular 4.0.0-beta.8 and typescript 2.2.0

ERROR in ./~/angular2-notifications/src/push-notifications.service.ts
Module build failed: Error: Typescript emitted no output for ...\node_modules\angular2-notifications\src\push-notifications.service.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at Object.loader (...\node_modules\ts-loader\dist\index.js:32:15)
 @ ./~/angular2-notifications/components.js 14:35-78

**Comment by rmannibucau** [comment] 2017-03-08 18:43
same there with angular 4 rc2 and webpack/typescript

**Comment by juliusl** [comment] 2017-03-30 19:17
@rmannibucau This fixed my issue for a completely different package. Why does that work?

**Comment by rmannibucau** [comment] 2017-03-30 19:53
cause webpack will match the file resolution in this "order". The issue is the ts not being supported anymore (nothing to convert to js basically). Loading the js before you will get a version not going through the exact same validations and or based on a different model (depends a bit other parts of the build). Concretely in that case the "empty" ts file is not seen and the build sees an actual js file which doesnt break the validations rules.

**Comment by juliusl** [comment] 2017-03-30 20:34
@rmannibucau Thanks for the explanation, it makes a lot more sense now.

**Comment by flauc** [comment] 2017-04-09 19:31
Hi everyone, think this has been resolved with the latest push, let me know if you are still getting it though.

**Closed by flauc** 2017-04-09 19:31 UTC
Labels: bug

**Comment by edzillion** [comment] 2017-06-26 09:54
This is still happening to me and was resolved by changing the order of extensions as suggested above:

```
File: node_modules\@ionic\app-scripts\config\webpack.config.js
15:   resolve: {
16:     extensions: ['.js', '.ts', '.json'],
17:     modules: [path.resolve('node_modules')]
18:   },
```

thanks!
