### ISSUE TITLE
Notification don't work

### ISSUE THREAD

**Issue by gleisonpc** [flauc/angular2-notifications#29] opened 2016-06-01 01:00 UTC
Hello,

I'm trying to use the notification, but i'm with a problem.

When I call the method sucess in my event onclick the notification work very well, but when I call the method inside other method called from the method called from the event click, dont work.

If I force the change in page so it's works!

Plis, anyone could help me?

Thanks!

**Comment by flauc** [comment] 2016-06-01 06:37
Hi, 

I'm having trouble understanding what the problem is. Could you provide a sample of the code please?

**Comment by gleisonpc** [comment] 2016-06-01 12:38
Of Course.

Lets Go:

My template:
<button class="btn btn-default" (click)="addAluno()">Salvar</button>

My component:
addAluno () {
        this._notificationService.info(
                'example', 
                'example', 
                {
                    timeOut: 0,
                    showProgressBar: true,
                    pauseOnHover: false,
                    clickToClose: true,
                    maxLength: 10
               }
           );
    }

It's works!

My template:
<button class="btn btn-default" (click)="addAluno()">Salvar</button>

My component:
addAluno () {
        this.salvarAluno()
    }

salvarAluno(){
        this.model.Cpf = jQuery("#cpf").val();        
        
        this._alunoService.addAluno(this.model)
                        .subscribe(
                            aluno => this.verificarAluno(aluno),
                            error =>  this.errorMessage = <any>error);
    }

verificarAluno(aluno: Aluno){
        if(aluno.IdAluno > 0){
           console.log(aluno);
           
           this.model = new Aluno();
           jQuery("#cpf").val('');
           
           this._applicationRef.tick();

           this._notificationService.success(
                'example', 
                'example', 
                {
                    timeOut: 5000,
                    showProgressBar: true,
                    pauseOnHover: false,
                    clickToClose: false,
                    maxLength: 10
                }
           );
        }
    }

This don't work normaly.

The element is createad, but dont show in my page:

![image](https://cloud.githubusercontent.com/assets/5217623/15709717/94b62fb2-27dc-11e6-9b5c-90a2ebd34508.png)

Thans for help me!

**Comment by flauc** [comment] 2016-06-01 12:51
Hmm.. Did you try moving the `this._notificationService.success()` call before the `this._applicationRef.tick();`?

**Comment by flauc** [comment] 2016-06-01 12:54
Maybe this could be the issue: 

> in development mode, tick() also performs a second change detection cycle to ensure that no further changes are detected...

[ApplicationRef](https://angular.io/docs/ts/latest/api/core/index/ApplicationRef-class.html)

**Comment by gleisonpc** [comment] 2016-06-01 13:02
I used tick() just to try make the sucess work.

Without them dont work too.

**Comment by flauc** [comment] 2016-06-02 06:23
Can you try and recreate the problem in a plunker? 
I tried to recreate it locally but couldn't get the same bug.

**Comment by gleisonpc** [comment] 2016-06-03 02:03
I'll try and back here!

Thanks!

**Comment by flauc** [comment] 2016-07-01 17:46
Hi @gleisonpc,

Didn't hear from you in a awhile, did you manage to get it to work, can i close the issue?

**Closed** 2016-07-07 18:42 UTC
